server:
  port: 9876

#eureka server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.30:9101/eureka/

  instance:
    prefer-ip-address: true
    instance-id: 192.168.31.30:9081

# 数据库配置
spring:
 #数据源
  datasource:
    url: jdbc:mysql://192.168.31.30:3306/app_all?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: jigu
    password: jigu123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize:  1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

  #redis
  redis:
    host: 192.168.31.30
    port: 63799
    timeout: 20000
#    password: jigu123

logging:
  level: DEBUG
  file: /var/log/cloud-admin.log

#  redis:
#      host: 192.168.145.132
#      port: 6379
#      timeout: 20000
#      cluster:
#          nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
#          maxRedirects: 6
#      pool:
#          max-active: 8
#          min-idle: 0
#          max-idle: 8
#          max-wait: -1
