server:
  port: 80

#eureka server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:jigu123456@127.0.0.1:9001/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# 数据库配置
spring:
 #数据源
  datasource:
    url: jdbc:mysql://120.76.28.91:3306/app_all?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: LLNjVPsnQX2NB16R
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize:  1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/**
#        allow:  //白名单
#        deny: //黑名单
