server:
  port: 9876


# 数据库配置
spring:
 #数据源
  datasource:
    url: jdbc:mysql://192.168.31.30:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: jigu
    password: jigu123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize:  1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

  #redis
  redis:
    host: 192.168.31.30
    port: 63799
    timeout: 20000

logging:
  level: DEBUG
